version: "3.8"

services:
   app:
      build: .
      ports:
         - "8080:8080"
      environment:
         SPRING_DATASOURCE_URL: ${MYSQL_URL}
         SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
         SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
